services:
  - type: web
    name: website-scanner
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: h2
